=== RSuiteCMS/team-edition-metadata-plugin/src/main/resources/doctypes/lmd-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!--<xs:import namespace="http://www.rsuitecms.com/rsuite/ns/metadata" />-->
    <xs:element name="lmd-param">
        <xs:complexType>
            <xs:attribute name="ref" type="xs:string" use="required"/>
            <xs:attribute default="false" name="allow-multiple" type="xs:boolean" use="optional"/>
            <xs:attribute default="text" name="control-type" type="xs:string" use="optional"/>
            <xs:attribute default="false" name="allow-user-entry" type="xs:boolean" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="lmd-search">
        <xs:complexType>
          <xs:sequence>
              <xs:element ref="lmd-param" maxOccurs="unbounded" minOccurs="0" />
          </xs:sequence>
          <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="label" type="xs:string" use="optional" />
          <xs:attribute name="description" type="xs:string" use="optional"/>
          <xs:attribute name="instructions" type="xs:string" use="optional"/>
          <xs:attribute name="roles" type="xs:string" use="optional"/>
          <xs:attribute name="icon" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="lmd-edit">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="lmd-param" maxOccurs="unbounded" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="label" type="xs:string" use="optional" />
            <xs:attribute name="description" type="xs:string" use="optional"/>
            <xs:attribute name="instructions" type="xs:string" use="optional"/>
            <xs:attribute name="roles" type="xs:string" use="optional"/>
            <xs:attribute name="icon" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="lmd-field">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="options" minOccurs="0" maxOccurs="1" />
               <xs:element ref="applies-to" minOccurs="0" maxOccurs="1" />
           </xs:sequence>
           <xs:attribute name="name" type="xs:string" use="required"/>
           <xs:attribute name="label" type="xs:string" use="optional" default="" />
           <xs:attribute name="description" type="xs:string" default="" use="optional"/>
           <xs:attribute default="true" name="contextual" type="xs:boolean" use="optional"/>
           <xs:attribute default="false" name="versioned" type="xs:boolean" use="optional"/>
           <xs:attribute default="false" name="allow-multiple" type="xs:boolean" use="optional"/>
           <xs:attribute default="text" name="control-type" type="xs:string" use="optional"/>
       </xs:complexType>
    </xs:element>
	<xs:element name="applies-to">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="elements" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="containers" minOccurs="0" maxOccurs="unbounded" />
			    <xs:element ref="files" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="elements">
       <xs:complexType>
			<xs:attribute name="namespace-uri" type="xs:string" use="optional" />
			<xs:attribute name="local-name" type="xs:string" use="required" />
       </xs:complexType>
    </xs:element>
    <xs:element name="containers">
       <xs:complexType>
			<xs:attribute name="type" type="xs:string" use="required" />
       </xs:complexType>
    </xs:element>
    <xs:element name="files">
        <xs:complexType>
            <xs:attribute name="extension" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>
    <xs:element name="options">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="option" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType>
			<xs:attribute name="label" type="xs:string" use="optional" />
			<xs:attribute name="value" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:element name="lmd-configuration">
       <xs:complexType>
           <xs:sequence maxOccurs="unbounded" minOccurs="0">
               <xs:element maxOccurs="unbounded" minOccurs="0" ref="lmd-field" />
               <xs:element maxOccurs="unbounded" minOccurs="0" ref="lmd-search"/>
               <xs:element maxOccurs="unbounded" minOccurs="0" ref="lmd-edit"/>
           </xs:sequence>
           <xs:attribute name="name" use="required" type="xs:string"/>
       </xs:complexType>
    </xs:element>
</xs:schema>

=== RSuiteCMS/team-edition-metadata-plugin/docs/sampleMdConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<lmd-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Sample LMD Config"
    xsi:noNamespaceSchemaLocation="../doctypes/lmd-configuration.xsd">
    <lmd-field contextual="true" description="Workflow status" label="Status" name="status"
        versioned="false">
        <options>
            <option label="Open" value="open"/>
            <option label="Ready" value="ready"/>
            <option label="In Progress" value="in-progress"/>
            <option label="Committed" value="committed"/>
            <option label="In QA" value="in-qa"/>
            <option label="Resolved" value="resolved"/>
            <option label="Closed" value="closed"/>
        </options>
        <applies-to>
            <containers type="folder"/>
            <elements local-name="lmd-configuration"/>
            <files extension="jpg"/>
            <files extension="png"/>
            <files extension="gif"/>
        </applies-to>
    </lmd-field>
    <lmd-field allow-multiple="true" contextual="true" description="Filesize" label="Size"
        name="size"
        versioned="false">
        <applies-to>
            <files/>
        </applies-to>
    </lmd-field>
    <lmd-field allow-multiple="true" contextual="true" description="Permission type"
        label="Permission type"
        name="permissionType"
        versioned="false">
        <options>
            <option label="Digital" value="digital"/>
            <option label="Print" value="print"/>
        </options>
        <applies-to>
            <files/>
        </applies-to>
    </lmd-field>
    <lmd-field allow-multiple="false" contextual="true" description="Reuse permissions"
        label="Reuse permissions"
        name="reusePermissions"
        versioned="false">
        <options>
            <option label="None" value="none"/>
            <option label="Unlimited" value="unlimited"/>
        </options>
        <applies-to>
            <files/>
        </applies-to>
    </lmd-field>
    <lmd-field contextual="true" description="Tag" label="Tag" name="Tag" versioned="false" allow-multiple="false" >
        <applies-to>
            <files/>
        </applies-to>
    </lmd-field>
    <lmd-search description="" instructions="" label="Search by metadata" name="metadataSearch">
        <lmd-param control-type="select" ref="status"/>
        <lmd-param allowMultiple="true" control-type="multiselect" ref="tag"/>
        <lmd-param control-type="select" ref="permissionType"/>
        <lmd-param control-type="select" ref="reusePermissions"/>
    </lmd-search>
    <lmd-edit description="" instructions="" label="Tags" name="metadataEdit">
        <lmd-param control-type="select" ref="status"/>
        <lmd-param allow-multiple="true" control-type="input" ref="tag"/>
    </lmd-edit>
    <lmd-edit description="" instructions="" label="Permissions" name="permissionsEdit">
        <lmd-param allow-multiple="true" control-type="checkbox" ref="permissionType"/>
        <lmd-param allow-multiple="false" control-type="select" ref="reusePermissions"/>
    </lmd-edit>
</lmd-configuration>

=== RSuiteCMS/team-edition-metadata-plugin/src/main/resources/lmd-sample/lmd-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<lmd-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../doctypes/lmd-configuration.xsd"
 name="Sample LMD Config">
    <lmd-field name="status" versioned="false" label="Status" contextual="true" description="Workflow status">
		<options>
			<option value="open" label="Open" />
			<option value="ready" label="Ready" />
			<option value="in-progress" label="In Progress" />
			<option value="committed" label="Committed" />
			<option value="in-qa" label="In QA" />
			<option value="resolved" label="Resolved" />
			<option value="closed" label="Closed" />
		</options>
		<applies-to>
			<containers type="folder" />
			<elements local-name="lmd-configuration" />
			<files extension="jpg" />
			<files extension="png" />
			<files extension="gif" />
		</applies-to>
    </lmd-field>
	<lmd-field name="size" versioned="false" label="Size" allow-multiple="true" contextual="true" description="Filesize">
		<applies-to>
			<files />
		</applies-to>
	</lmd-field>
	<lmd-field name="argle-bargle" versioned="false" label="Size" contextual="true" description="Filesize">
		<applies-to>
			<files />
		</applies-to>
	</lmd-field>
    <lmd-search name="statusSearch" label="Search by status" description="" instructions="">
        <lmd-param ref="status" control-type="checkbox"/>
    </lmd-search>
    <lmd-edit name="statusEdit" label="Edit status" description="" instructions="">
        <lmd-param ref="status" control-type="select"/>
		<lmd-param ref="size" control-type="input"/>
    </lmd-edit>
</lmd-configuration>
